apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_PUBLIC_API_URL: "http://expense-api-service:3001/api"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: expense-postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: expense-postgres
  template:
    metadata:
      labels:
        app: expense-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "supersecret"
            - name: POSTGRES_DB
              value: "expense_db"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: expense-postgres-service
spec:
  ports:
    - port: 5432
  selector:
    app: expense-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      containers:
        - name: api
          image: expense-manager-api:latest
          env:
            - name: DATABASE_URL
              value: "postgres://admin:supersecret@expense-postgres-service:5432/expense_db"
            - name: JWT_SECRET
              value: "production_secure_jwt_secret_signature"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: expense-api-service
spec:
  ports:
    - port: 3001
      targetPort: 3000
  selector:
    app: expense-api
